### ISSUE TITLE
Run this with serverless ? 

### ISSUE THREAD

**Issue by vallard** [KoteiIto/node-athena#1]
Hi I'd like to use this library with the serverless project (https://serverless.com/framework/) is there any samples on how to make this work, or is it not in the scope of this project?  Thanks for the great code!

**Comment by KoteiIto** [comment]
@vallard 
This library can be use in serverless project.
Here is the sample code of lambda handler.

```js
'use strict'

var Athena = require('athena-client')

var credentials = {
  accessKeyId: 'XXXX',
  secretAccessKey: 'XXXX',
  region: 'XXXX',
}
var config = {
  bucketUri: 's3://XXXX'
}

module.exports.hello = (event, context, callback) => {
  var client = Athena.Client(credentials, config)
  client.execute('SELECT 1', function (err, result) {
    if (err) {
      return callback(err)
    }
    callback(null, result);
  })
}
```

**Comment by vallard** [comment]
Thank you so much for going to the trouble to write that up!  That looks pretty good and I'll take a look.
