### ISSUE TITLE
athena-client is 7x slower than athena editor

### ISSUE THREAD

**Issue by Meenakshi14** [KoteiIto/node-athena#14]

**Comment by KoteiIto** [comment]
it may take time to get results.
In athena's editor, the result is asynchronously displayed according to scroll when the number of results is large, but in version 1.x, callback is executed when all the results are acquired.
If you use the 2.x stream, both the end of the query and getting result event will fire, so can you try it out there?
```
npm install athena-client@beta
```
https://github.com/KoteiIto/node-athena/tree/2.x
