### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by EugeneHerasymchuk** [KoteiIto/node-athena#23]
This problem appears approximately every time I use `execute(sql).toPromise()`
After debugging I noticed that error throws in this place

https://github.com/KoteiIto/node-athena/blob/a3f84b9d8659dbae245585435a34f237a023ac1e/build/lib/stream.js#L66

> TypeError: Cannot read property 'length' of undefined
> at AthenaStream.<anonymous> (/var/task/node_modules/athena-client/build/lib/stream.js:93:40)
> at next (native)
> at fulfilled (/var/task/node_modules/athena-client/build/lib/stream.js:4:58)

The version of `athena-client` is `2.0.0`

**Comment by KoteiIto** [comment]
In v2.0.0, bugs may occur in parsing csv.
Can you use v2.1.0 or higher.

**Comment by EugeneHerasymchuk** [comment]
Thank you. 
For anyone with the problem. I installed `2.1.2` version and this error was gone.
