### ISSUE TITLE
Return the query Id as well as its results

### ISSUE THREAD

**Issue by orlavy-bigabid** [KoteiIto/node-athena#7]
Hey, I would like to ask for the addition of the query id to the return value of the 'execute' method.
That will enable us to get the query results from Athena without re-querying (And will greatly reduce the bills).

**Comment by KoteiIto** [comment]
Thank you for creating issue. Next major version update will support to get uri of result in s3.
 https://github.com/KoteiIto/node-athena/pull/11

**Comment by adim** [comment]
when version 2.x will be available in https://www.npmjs.com/package/athena-client?

**Comment by KoteiIto** [comment]
you can install 2.x as follows.
```
npm intall athena-client@beta
```
If bugs are not reported, we plan to delete the beta tag in January.

**Comment by KoteiIto** [comment]
2.x is released.
